{
    "docs": "https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/compile.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test compile --python 3.5` [[explain](https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/compile.html)] failed with 29 errors:", 
            "output": ".venv/lib/python3.8/site-packages/ansible_collections/netbox/netbox/docs/conf.py:87:140: SyntaxError: args_string = f\"junk plugin --dest-dir plugins/{plugin_type}/{file_name}/ --plugin-type {plugin_type} netbox.netbox.{file_name}\"\n.venv/lib/python3.8/site-packages/ansible_collections/netbox/netbox/tests/test_data.py:14:55: SyntaxError: with open(f\"{path}/test_data/{test_path}/data.json\", \"r\") as f:\n.venv/lib/python3.8/site-packages/attr/_next_gen.py:37:1: SyntaxError: ):\n.venv/lib/python3.8/site-packages/django/contrib/postgres/constraints.py:15:5: SyntaxError: ):\n.venv/lib/python3.8/site-packages/django/contrib/postgres/search.py:242:5: SyntaxError: ):\n.venv/lib/python3.8/site-packages/django/db/backends/postgresql/schema.py:201:5: SyntaxError: ):\n.venv/lib/python3.8/site-packages/django/db/models/fields/json.py:26:17: SyntaxError: **kwargs,\n.venv/lib/python3.8/site-packages/django/test/client.py:526:30: SyntaxError: secure=False, **extra,\n.venv/lib/python3.8/site-packages/jinja2/asyncsupport.py:198:31: SyntaxError: iterable = [x async for x in self._iterator]\n.venv/lib/python3.8/site-packages/magicmock/ClientAPI/__init__.py:34:47: SyntaxError: print \"unrecognized path list!\"\n.venv/lib/python3.8/site-packages/magicmock/Http/HttpHandler.py:72:25: SyntaxError: except Exception, e:\n.venv/lib/python3.8/site-packages/magicmock/Http/MockController.py:71:18: SyntaxError: print response\n.venv/lib/python3.8/site-packages/magicmock/Http/web/application.py:284:33: SyntaxError: except web.HTTPError, e:\n.venv/lib/python3.8/site-packages/magicmock/Http/web/browser.py:49:30: SyntaxError: print 'requesting', req.get_method(), req.get_full_url()\n.venv/lib/python3.8/site-packages/magicmock/Http/web/db.py:81:32: SyntaxError: raise UnknownParamstyle, paramstyle\n.venv/lib/python3.8/site-packages/magicmock/Http/web/debugerror.py:283:25: SyntaxError: except Exception, e:\n.venv/lib/python3.8/site-packages/magicmock/Http/web/form.py:100:23: SyntaxError: raise KeyError, i\n.venv/lib/python3.8/site-packages/magicmock/Http/web/httpserver.py:75:36: SyntaxError: except socket.error, socket_err:\n.venv/lib/python3.8/site-packages/magicmock/Http/web/net.py:120:29: SyntaxError: raise ValueError, ':'.join(ip) + ' is not a valid IP address/port'\n.venv/lib/python3.8/site-packages/magicmock/Http/web/python23.py:17:41: SyntaxError: raise AttributeError, name\n.venv/lib/python3.8/site-packages/magicmock/Http/web/session.py:239:29: SyntaxError: raise ValueError, \"Bad key: %s\" % repr(key)\n.venv/lib/python3.8/site-packages/magicmock/Http/web/template.py:469:29: SyntaxError: raise ParseError, 'Unknown statement: %s' % repr(keyword)\n.venv/lib/python3.8/site-packages/magicmock/Http/web/utils.py:75:24: SyntaxError: except KeyError, k:\n.venv/lib/python3.8/site-packages/magicmock/Http/web/webapi.py:270:25: SyntaxError: raise ValueError, 'invalid characters in header'\n.venv/lib/python3.8/site-packages/magicmock/Http/web/wsgiserver/__init__.py:616:26: SyntaxError: except ValueError, ex:\n.venv/lib/python3.8/site-packages/magicmock/Http/web/wsgiserver/ssl_builtin.py:43:28: SyntaxError: except ssl.SSLError, e:\n.venv/lib/python3.8/site-packages/magicmock/Http/web/wsgiserver/ssl_pyopenssl.py:70:36: SyntaxError: except SSL.SysCallError, e:\n.venv/lib/python3.8/site-packages/magicmock/Utils.py:170:18: SyntaxError: print self.method.upper() + ' ' + url\n.venv/lib/python3.8/site-packages/magicmock/__init__.py:80:48: SyntaxError: print \"Usage: magicmocksetup <dest dir>\""
        }
    ], 
    "verified": false
}
